name: Scrape Stats

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm i
      - name: Scrape
        run: |
          set -e
          { cat data.jsonl.gz | gunzip -c ; node scrape.js; }
          # { cat data.jsonl.gz | gunzip -c ; node scrape.js; } | gzip > data.jsonl.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLIC_GITHUB_TOKEN: ${{ secrets.PUBLIC_GITHUB_TOKEN }}
      - name: Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "8732198738+github-actions[bot]@users.noreply.github.com"
          git add data.jsonl.gz
          git commit -am "Update data.jsonl.gz"
          git push
